import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://sndrydocktest.azurewebsites.net/arinvoiceqatest');
  await page.getByRole('textbox', { name: 'Enter Username' }).click();
  await page.getByRole('textbox', { name: 'Enter Username' }).fill('balasubu');
  await page.getByRole('textbox', { name: 'Enter Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter Password' }).fill('Shipnet1');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('menuitem', { name: 'New' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('menuitem', { name: 'Fund Request' }).click();
  const page1 = await page1Promise;
  await page1.locator('.dxbl-btn.dxbl-btn-outline-secondary').first().click();
  await page1.getByRole('cell', { name: 'BUDGET NEW' }).click();
  await page1.locator('input[name="cboShipCode"]').click();
  await page1.locator('input[name="cboShipCode"]').fill('turc');
  await page1.getByRole('cell', { name: 'TURC' }).locator('div').click();
  await page1.locator('#idddae3bad-5285-4f14-83fd-3eb010d45549 > .dxbl-btn-group > .dxbl-btn').click();
  await page1.getByRole('cell', { name: '202511' }).click();
  await page1.locator('#id2c949be7-363d-4b1a-9ea6-50a208b4fd8a > .dxbl-btn-group > .dxbl-btn').click();
  await page1.getByRole('cell', { name: '202512' }).click();
  await page1.locator('#ide9b6380a-15f3-418e-a557-e719df61e1ca > .dxbl-btn-group > .dxbl-btn').click();
  await page1.getByRole('button', { name: 'Today' }).click();
  await page1.locator('#ida2997441-6659-42a8-8c75-14707587b3c1').getByRole('button', { name: 'Open or close the drop-down' }).click();
  await page1.getByRole('cell', { name: '1' }).click();
  await page1.getByRole('group').getByRole('button', { name: 'Save' }).click();
  await page1.locator('dxbl-scroll-viewer').filter({ hasText: 'Line Code Account Number' }).locator('dxbl-thumb').nth(1).click();
  await page1.locator('td:nth-child(12)').first().click();
  await page1.locator('td:nth-child(12)').first().click();
  await page1.getByRole('gridcell', { name: 'Open or close the drop-down window ' }).getByLabel('Open or close the drop-down').click();
  await page1.getByRole('cell', { name: 'ANTW-Contnr 6+damage rough sea' }).click();
  await page1.locator('tr:nth-child(2) > td:nth-child(12)').click();
  await page1.getByRole('gridcell', { name: 'Open or close the drop-down window ' }).getByLabel('Open or close the drop-down').click();
  await page1.getByRole('cell', { name: 'ANTW-Contnr 6+damage rough sea' }).click();
  await page1.getByRole('group').getByRole('button', { name: 'Save' }).click();
  await page1.getByRole('button', { name: 'Workflow' }).click();
  await page1.getByRole('button', { name: 'icon: close' }).click();
  await page1.getByRole('button', { name: 'Approve' }).click();
  await page1.getByRole('button', { name: 'Confirm' }).click();
  await page1.getByRole('button', { name: 'Workflow' }).click();
  await page1.getByRole('button', { name: 'Transfer', exact: true }).click();
  await page1.getByRole('button', { name: 'Confirm' }).click();
  await page1.getByRole('button', { name: 'Preview' }).click();
  await page1.getByRole('button', { name: '' }).click();
  await page1.getByRole('button', { name: 'More items...' }).click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('menuitemcheckbox', { name: 'Create Credit Note' }).click();
  const page2 = await page2Promise;
  await page2.getByRole('group').getByRole('button', { name: 'Save' }).click();
  await page2.getByRole('button', { name: 'Workflow' }).click();
  await page2.getByRole('button', { name: 'icon: close' }).click();
  await page2.getByRole('button', { name: 'Approve' }).click();
  await page2.getByRole('button', { name: 'Confirm' }).click();
  await page2.getByRole('button', { name: 'Workflow' }).click();
  await page2.getByRole('button', { name: 'Transfer', exact: true }).click();
  await page2.getByRole('button', { name: 'Confirm' }).click();
});