import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://sndrydocklive-staging.azurewebsites.net/shipnetdemo');
  await page.getByRole('textbox', { name: 'Enter Username' }).click();
  await page.getByRole('textbox', { name: 'Enter Username' }).fill('ash');
  await page.getByRole('textbox', { name: 'Enter Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter Password' }).fill('ashash');
  await page.getByRole('textbox', { name: 'Enter Password' }).press('Tab');
  await page.getByRole('button', { name: 'Login' }).press('Tab');
  await page.getByRole('link', { name: 'Login With Microsoft Account' }).press('Enter');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.locator('#MainMenu').click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByText('AR Invoice').click();
  const page1 = await page1Promise;
  await page1.getByRole('link', { name: '*P*001123' }).click({
    button: 'middle'
  });
  await page2.getByRole('button', { name: '', exact: true }).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-thumb').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-thumb').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-thumb').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-thumb').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-thumb').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-thumb').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-thumb').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-thumb').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-scroll-bar').nth(1).click();
  await page2.getByRole('dialog', { name: 'Edit Information' }).locator('dxbl-thumb').nth(1).click();
  await page2.getByRole('button', { name: 'OK' }).click();
  await page2.locator('dxbl-scroll-viewer').filter({ hasText: 'Line Code Account Number' }).locator('dxbl-thumb').nth(1).click();
  await page2.locator('dxbl-scroll-viewer').filter({ hasText: 'Line Code Account Number' }).locator('dxbl-thumb').nth(1).click();
  await page2.locator('#ide5d6ab63-0603-4836-8500-329d394dedb6').uncheck();
  await page2.getByRole('group').getByRole('button', { name: 'Save' }).click();
  await page2.getByRole('gridcell', { name: 'Open or close the drop-down window', exact: true }).getByLabel('Open or close the drop-down').click();
  await page2.getByText('Document Type Voucher Style').click();
  await page2.getByRole('button', { name: '', exact: true }).click();
  await page2.getByRole('button', { name: 'OK' }).click();
  await page2.getByRole('gridcell', { name: 'Open or close the drop-down window', exact: true }).getByLabel('', { exact: true }).click();
  await page2.getByRole('gridcell', { name: 'Open or close the drop-down window', exact: true }).getByLabel('', { exact: true }).fill('53');
  await page2.getByText('5301009').click();
  await page2.getByRole('group').getByRole('button', { name: 'Save' }).click();
});