import { test, expect } from '@playwright/test';

test('test', async ({ page }) => {
  await page.goto('https://sndrydocktest.azurewebsites.net/arinvoiceqatest');
  await page.getByRole('textbox', { name: 'Enter Username' }).click();
  await page.getByRole('textbox', { name: 'Enter Username' }).fill('balasubu');
  await page.getByRole('textbox', { name: 'Enter Username' }).press('Tab');
  await page.getByRole('textbox', { name: 'Enter Password' }).fill('Shipnet1');
  await page.getByRole('button', { name: 'Login' }).click();
  await page.getByRole('menuitem', { name: 'New' }).click();
  const page1Promise = page.waitForEvent('popup');
  await page.getByRole('menuitem', { name: 'Fund Request' }).click();
  const page1 = await page1Promise;
  await page1.locator('.dxbl-btn.dxbl-btn-outline-secondary').first().click();
  await page1.getByRole('cell', { name: 'BUDGET NEW' }).click();
  await page1.locator('input[name="cboShipCode"]').click();
  await page1.locator('input[name="cboShipCode"]').fill('tur');
  await page1.getByText('TURC').click();
  await page1.locator('#idba4ca352-f938-4034-b672-837b39af5751 > .dxbl-btn-group > .dxbl-btn').click();
  await page1.getByRole('cell', { name: '202511' }).click();
  await page1.locator('#idf7a71186-ee41-48d7-be53-69ec13058dea > .dxbl-btn-group > .dxbl-btn').click();
  await page1.getByRole('cell', { name: '202512' }).click();
  await page1.locator('#id1ad6e220-0ab8-4649-94f3-445c7bb3f490 > .dxbl-btn-group > .dxbl-btn').click();
  await page1.getByText('30').nth(4).click();
  await page1.locator('dxbl-scroll-viewer').filter({ hasText: 'Line Code Account Number' }).locator('dxbl-thumb').nth(1).click();
  await page1.locator('dxbl-scroll-viewer').filter({ hasText: 'Line Code Account Number' }).locator('dxbl-thumb').nth(1).click();
  await page1.locator('dxbl-scroll-viewer').filter({ hasText: 'Line Code Account Number' }).locator('dxbl-scroll-bar').nth(1).click();
  await page1.locator('dxbl-scroll-viewer').filter({ hasText: 'Line Code Account Number' }).locator('dxbl-thumb').nth(1).click();
  await page1.locator('dxbl-scroll-viewer').filter({ hasText: 'Line Code Account Number' }).locator('dxbl-thumb').nth(1).click();
  await page1.locator('td:nth-child(12)').first().click();
  await page1.getByRole('gridcell', { name: 'Open or close the drop-down window ' }).getByLabel('Open or close the drop-down').click();
  await page1.getByRole('cell', { name: 'ACAL-Cargo-Sea water ingress' }).click();
  await page1.getByRole('gridcell', { name: 'AF17144C Open or close the' }).locator('i').dblclick();
  await page1.locator('#id0a3367ac-9618-4c0c-a7e1-7088820e0c4d > .dxbl-btn-group > .dxbl-btn').click();
  await page1.getByRole('cell', { name: '1' }).click();
  await page1.getByRole('group').getByRole('button', { name: 'Save' }).click();
  await page1.getByRole('button', { name: 'Workflow' }).click();
  await page1.getByRole('button', { name: 'icon: close' }).click();
  await page1.getByRole('button', { name: 'Transfer' }).click();
  await page1.getByRole('button', { name: 'Confirm' }).click();
  await page1.getByRole('button', { name: 'More items...' }).click();
  await page1.getByRole('button', { name: 'More items...' }).click();
  await page1.getByRole('menuitemcheckbox', { name: 'Cr Note/Payment' }).click();
  const page2Promise = page1.waitForEvent('popup');
  await page1.getByRole('menuitemcheckbox', { name: 'Create Credit Note' }).click();
  const page2 = await page2Promise;
  await page2.getByRole('group').getByRole('button', { name: 'Save' }).click();
});